image: ghcr.io/${{ github.repository_owner }}/{arch}-base-python
build_from:
  aarch64: "ghcr.io/${{ github.repository_owner }}/aarch64-base:"
  armv7: "ghcr.io/${{ github.repository_owner }}/armv7-base:"
  armhf: "ghcr.io/${{ github.repository_owner }}/armhf-base:"
  amd64: "ghcr.io/${{ github.repository_owner }}/amd64-base:"
  i386: "ghcr.io/${{ github.repository_owner }}/i386-base:"
cosign:
  base_identity: https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/.*
  identity: https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/.*
args:
  PYTHON_VERSION: "3.11.13"
  PIP_VERSION: "25.2"
  CERT_IDENTITY: pablogsal@python.org
  CERT_OIDC_ISSUER: https://accounts.google.com
labels:
  io.hass.base.name: python
  org.opencontainers.image.source: https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}
