image: ghcr.io/eshattow/{arch}-base-python
build_from:
  aarch64: "ghcr.io/eshattow/aarch64-base:"
  armv7: "ghcr.io/eshattow/armv7-base:"
  armhf: "ghcr.io/eshattow/armhf-base:"
  amd64: "ghcr.io/eshattow/amd64-base:"
  i386: "ghcr.io/eshattow/i386-base:"
cosign:
  base_identity: https://github.com/eshattow/ha-docker-base/.*
  identity: https://github.com/eshattow/ha-docker-base/.*
args:
  PYTHON_VERSION: "3.11.13"
  PIP_VERSION: "25.2"
  CERT_IDENTITY: pablogsal@python.org
  CERT_OIDC_ISSUER: https://accounts.google.com
labels:
  io.hass.base.name: python
  org.opencontainers.image.source: https://github.com/eshattow/ha-docker-base
