image: ghcr.io/${{ github.repository_owner }}/{arch}-base-raspbian
build_from:
  armhf: "tianon/raspbian:"
cosign:
  identity: https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/.*
args:
  BASHIO_VERSION: 0.17.0
  TEMPIO_VERSION: 2024.11.2
  S6_OVERLAY_VERSION: 3.1.6.2
labels:
  io.hass.base.name: raspbian
  org.opencontainers.image.source: https://${{ github.repository_owner }}/${{ github.event.repository.name }}
